webnlp/urls.py
from django.contrib import admin
from django.urls import path

from core import views as core_views

urlpatterns = [
    path('', core_views.home,name='home'),
    path('base/', core_views.base,name='base'),
    path('info/', core_views.info,name='info'),
    path('slicing/', core_views.slicing,name='slicing'),
    path('results/', core_views.results,name='results'),
    path('resultsSlicing/', core_views.resultsSlicing,name='resultsSlicing'),
    path('team/', core_views.team,name='team'),
    path('text-analytics-details/', core_views.textAnalyticsDetails,name='textAnalyticsDetails'),
    path('automaticSlice/',core_views.AutomaticSlice,name='automaticSlice'),
    path('resultsAuto/',core_views.resultsAuto,name='resultsAuto'),
    path('admin/', admin.site.urls),
]

core/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms

class ParagraphForm(forms.Form):
    text = forms.CharField(label='text', required=True)
class SliceForm(forms.Form):
    text = forms.CharField(label='text', required=True)
    number = forms.IntegerField(label='number',required=True,max_value=5,min_value=1) 

core/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from .forms import ParagraphForm, SliceForm
from .analysis import trascender_summary, union_bigram, union_trigram, sentiment
from .sliceParagraph import raw2parr
from .autoSlice import raw2parr
from .gift import gif_url

# Create your views here.


def home(request):
    return render(request, 'core/home.html')


def slicing(request):
    if request.method == "POST":
        paragraph_form = SliceForm(data=request.POST)
        if paragraph_form.is_valid():
            text = request.POST.get('text', '')
            number = request.POST.get('number', '')
        return redirect(reverse('resultsSlicing')+'?'+number+text)
    else:
        return render(request, 'core/slicing.html')


def results(request):
    text = ""
    if request.method == "GET":
        for element in request.GET:
            text += element
    summary, lw, cb, ct, s = trascender_summary(text)
    title2, cb = union_bigram(cb)
    title3, ct = union_trigram(ct)
    s = sentiment(s)
    return render(request, 'core/results.html', {'summary': summary, 'lw': lw, 'cb': cb, 'ct': ct, 's': s, 'title2': title2, 'title3': title3})


def resultsSlicing(request):
    text = ""
    if request.method == "GET":
        for element in request.GET:
            text += element
        number = int(text[0])
        text = text[1:]
        text = raw2parr(text, number)
        summary_list = []
        title2_list = []
        title3_list = []
        s_list = []
        cb_list = []
        ct_list = []
        for p in text:
            summary, lw, cb, ct, s = trascender_summary(p)
            title2, cb = union_bigram(cb)
            title3, ct = union_trigram(ct)
            s = sentiment(s)
            summary_list.append(summary)
            title2_list.append(title2)
            title3_list.append(title3)
            s_list.append(s)
            cb_list.append(cb)
            ct_list.append(ct)
            output = zip(text, summary_list, title2_list,
                         title3_list, cb_list, ct_list, s_list)
    # return render(request,'core/resultsSlicing.html',{'text':text,'summary':summary_list,'cb':cb_list,'ct':ct_list,'s':s_list,'title2':title2_list,'title3':title3_list})
    return render(request, 'core/resultsSlicing.html', {'output': output})


def base(request):
    return render(request, 'core/base.html')


def info(request):
    return render(request, 'core/info.html')


def team(request):
    return render(request, 'core/team.html')


def textAnalyticsDetails(request):
    if request.method == "POST":
        paragraph_form = ParagraphForm(data=request.POST)
        if paragraph_form.is_valid():
            text = request.POST.get('text', '')
        return redirect(reverse('results')+'?'+text)
    else:
        return render(request, 'core/textAnalyticsDetails.html')


def AutomaticSlice(request):
    if request.method == "POST":
        paragraph_form = ParagraphForm(data=request.POST)
        if paragraph_form.is_valid():
            text = request.POST.get('text', '')
        return redirect(reverse('resultsAuto')+'?'+text)
    else:
        return render(request, 'core/automaticSlice.html')


def resultsAuto(request):
    text = ""
    title2_list = []
    title3_list = []
    url_gif = []
    if request.method == "GET":
        for element in request.GET:
            text += element

    paragraphs = raw2parr(text, 35)
    for p in paragraphs:
        _, _, cb, ct, _ = trascender_summary(p)
        title2, cb = union_bigram(cb)
        title2_list.append(title2)
        title3, ct = union_trigram(ct)
        title3_list.append(title3)
        url = gif_url(title2)
        url_gif.append(url)
    output = zip(paragraphs, title2_list, title3_list, url_gif)
    return render(request, 'core/resultsAuto.html', {'output': output})

core/templates/core/automaticSlice.html
{% extends 'core/base.html' %} {% load static %} {% block title%}Auto
Slice{%endblock %} {%block active_service%}active{%endblock%} {% block body%}

<section class="features">
  <div class="container">
    <div class="section-title">
      <h2>AUTO SLICING</h2>
      <p>
        Artificial intelligence does everything for you. Just paste a text and
        see how it works. Try it!
      </p>
    </div>
    <form action="" method="POST">
      {% csrf_token %}
    <tr>
      <td><textarea name="text" id="id_text" required cols="120" rows="10"></textarea></td>
      </tr>
    <p></p>
    <input type="submit" class="btn btn-primary" value="Send"></input>
  </form>
  </div>
</section>

{% endblock %}

core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />

    <title>{% block title %}Home{% endblock %}|Text Analytics</title>
    <meta content="" name="descriptison" />
    <meta content="" name="keywords" />

    <!-- Favicons -->
    {% load static %}
    <link href="{% static 'core/assets/img/logo.jpeg' %}" rel="icon" />
    <link
      href="{% static 'core/assets/img/apple-touch-icon.png' %}"
      rel="apple-touch-icon"
    />

    <!-- Google Fonts -->
    <link
      href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Roboto:300,300i,400,400i,500,500i,700,700i&display=swap"
      rel="stylesheet"
    />

    <!-- Vendor CSS Files -->
    <link
      href="{% static 'core/assets/vendor/bootstrap/css/bootstrap.min.css' %}"
      rel="stylesheet"
    />
    <link
      href="{% static 'core/assets/vendor/animate.css/animate.min.css' %}"
      rel="stylesheet"
    />
    <link
      href="{% static 'core/assets/vendor/icofont/icofont.min.css' %}"
      rel="stylesheet"
    />
    <link
      href="{% static 'core/assets/vendor/boxicons/css/boxicons.min.css' %}"
      rel="stylesheet"
    />
    <link
      href="{% static 'core/assets/vendor/venobox/venobox.css' %}"
      rel="stylesheet"
    />
    <link
      href="{% static 'core/assets/vendor/owl.carousel/assets/owl.carousel.min.css' %}"
      rel="stylesheet"
    />
    <link
      href="{% static 'core/assets/vendor/aos/aos.css' %}"
      rel="stylesheet"
    />

    <!-- Template Main CSS File -->
    <link href="{% static 'core/assets/css/style.css' %}" rel="stylesheet" />

    <!-- =======================================================
  * Template Name: Moderna - v2.0.1
  * Template URL: https://bootstrapmade.com/free-bootstrap-template-corporate-moderna/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
  </head>

  <body>
    <!-- ======= Header ======= -->
    <header id="header" class="fixed-top header-transparent">
      <div class="container">
        <div class="logo float-left">
          <h1 class="text-light">
            <a href="{%url 'home'%}"><span>Text Analytics</span></a>
          </h1>
          <!-- Uncomment below if you prefer to use an image logo -->
          <!-- <a href="index.html"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->
        </div>

        <nav class="nav-menu float-right d-none d-lg-block">
          <ul>
            <li class="{%block active_home%}{%endblock%}"><a href="{%url 'home'%}">Home</a></li>
            <li class="{%block active_info%}{%endblock%}"><a href="{% url 'info'%}">information</a></li>
            <li class="{%block active_team%}{%endblock%}"><a href="{% url 'team' %}">Team</a></li>
            <li class="{%block active_service%}{%endblock%} drop-down">
              <a href="">Services</a>
              <ul>
                <li><a href="{%url 'textAnalyticsDetails'%}">Text Analytics Details</a></li>
                <li><a href="{%url 'slicing' %}">Slicing</a></li>
                <li><a href="{%url 'automaticSlice' %}">Auto Slice</a></li>
              </ul>
            </li>
          </ul>
        </nav>
        <!-- .nav-menu -->
      </div>
    </header>
    <!-- End Header -->

    {% block Hero %} {% endblock %}
    <main id="main">
      {% block body %}{% endblock %}
      {% block services%}
      <!-- <section class="services">
      <div class="container">

        <div class="row">
          <div class="col-md-6 col-lg-3 d-flex align-items-stretch" data-aos="fade-up">
            <div class="icon-box icon-box-pink">
              <div class="icon"><i class="bx bxl-dribbble"></i></div>
              <h4 class="title"><a href="">Lorem Ipsum</a></h4>
              <p class="description">Voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident</p>
            </div>
          </div>

          <div class="col-md-6 col-lg-3 d-flex align-items-stretch" data-aos="fade-up" data-aos-delay="100">
            <div class="icon-box icon-box-cyan">
              <div class="icon"><i class="bx bx-file"></i></div>
              <h4 class="title"><a href="">Sed ut perspiciatis</a></h4>
              <p class="description">Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur</p>
            </div>
          </div>

          <div class="col-md-6 col-lg-3 d-flex align-items-stretch" data-aos="fade-up" data-aos-delay="200">
            <div class="icon-box icon-box-green">
              <div class="icon"><i class="bx bx-tachometer"></i></div>
              <h4 class="title"><a href="">Magni Dolores</a></h4>
              <p class="description">Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum</p>
            </div>
          </div>

          <div class="col-md-6 col-lg-3 d-flex align-items-stretch" data-aos="fade-up" data-aos-delay="200">
            <div class="icon-box icon-box-blue">
              <div class="icon"><i class="bx bx-world"></i></div>
              <h4 class="title"><a href="">Nemo Enim</a></h4>
              <p class="description">At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque</p>
            </div>
          </div>

        </div>

      </div>
    </section>End Services Section -->
      {% endblock %}

      {% block why-us%}{% endblock %}

      {% block features %}{% endblock %}
    </main>
    <!-- End #main -->

    <!-- ======= Footer ======= -->
    <footer
      id="footer"
      data-aos="fade-up"
      data-aos-easing="ease-in-out"
      data-aos-duration="500"
    >
      <div class="footer-top">
        <div class="container">
          <div class="row">
            <div class="col-lg-4 col-md-6 footer-links">
              <h4>Useful Links</h4>
              <ul>
                <li>
                  <i class="bx bx-chevron-right"></i> <a href="{% url 'home' %}">Home</a>
                </li>
                <li>
                  <i class="bx bx-chevron-right"></i> <a href="{% url 'info' %}">Information</a>
                </li>
                <li>
                  <i class="bx bx-chevron-right"></i> <a href="{% url 'team' %}">Team</a>
                </li>
                <li>
                  <i class="bx bx-chevron-right"></i> <a href="{% url 'textAnalyticsDetails' %}">Try Simple Demo</a>
                </li>
                <li>
                  <i class="bx bx-chevron-right"></i> <a href="{% url 'slicing' %}">Try a Slicing Demo</a>
                </li>
              </ul>
            </div>

            <!-- <div class="col-lg-3 col-md-6 footer-links">
              <h4>Our Services</h4>
              <ul>
                <li>
                  <i class="bx bx-chevron-right"></i> <a href="#">Web Design</a>
                </li>
                <li>
                  <i class="bx bx-chevron-right"></i>
                  <a href="#">Web Development</a>
                </li>
                <li>
                  <i class="bx bx-chevron-right"></i>
                  <a href="#">Product Management</a>
                </li>
                <li>
                  <i class="bx bx-chevron-right"></i> <a href="#">Marketing</a>
                </li>
                <li>
                  <i class="bx bx-chevron-right"></i>
                  <a href="#">Graphic Design</a>
                </li>
              </ul>
            </div> -->

            <div class="col-lg-4 col-md-6 footer-contact">
              <h4>Contact Us</h4>
              <p>
                Planet Earth <br />
                <br />
                <strong>Phone:</strong> +1 00 000 00<br />
                <strong>Email:</strong> info@example.com<br />
              </p>
            </div>

            <div class="col-lg-4 col-md-6 footer-info">
              <h3>About Text Analytics</h3>
              <p>
                This website is made with artificial intelligence techniques that support the productive sector in the 4.0 revolution. It can be quite scalable to extract information from texts and make decision making much more efficient.
              </p>
              <div class="social-links mt-3">
                <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
                <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
                <a href="#" class="instagram"
                  ><i class="bx bxl-instagram"></i
                ></a>
                <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="container">
        <div class="copyright">
          &copy; Copyright <strong><span>Moderna</span></strong
          >. All Rights Reserved
        </div>
        <div class="credits">
          <!-- All the links in the footer should remain intact. -->
          <!-- You can delete the links only if you purchased the pro version. -->
          <!-- Licensing information: https://bootstrapmade.com/license/ -->
          <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/free-bootstrap-template-corporate-moderna/ -->
          Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
        </div>
      </div>
    </footer>
    <!-- End Footer -->

    <a href="#" class="back-to-top"><i class="icofont-simple-up"></i></a>

    <!-- Vendor JS Files -->
    <script src="{% static 'core/assets/vendor/jquery/jquery.min.js'%}"></script>
    <script src="{% static 'core/assets/vendor/bootstrap/js/bootstrap.bundle.min.js'%}"></script>
    <script src="{% static 'core/assets/vendor/jquery.easing/jquery.easing.min.js'%}"></script>
    <script src="{% static 'core/assets/vendor/php-email-form/validate.js'%}"></script>
    <script src="{% static 'core/assets/vendor/venobox/venobox.min.js'%}"></script>
    <script src="{% static 'core/assets/vendor/waypoints/jquery.waypoints.min.js'%}"></script>
    <script src="{% static 'core/assets/vendor/counterup/counterup.min.js'%}"></script>
    <script src="{% static 'core/assets/vendor/owl.carousel/owl.carousel.min.js'%}"></script>
    <script src="{% static 'core/assets/vendor/isotope-layout/isotope.pkgd.min.js'%}"></script>
    <script src="{% static 'core/assets/vendor/aos/aos.js' %}"></script>

    <!-- Template Main JS File -->
    <script src="{% static 'core/assets/js/main.js'%}"></script>
  </body>
</html>

core/templates/core/home.html
{% extends 'core/base.html' %}

{% load static %}

{% block title %}Home{% endblock %}
{%block active_home%}active{% endblock %}
{% block Hero %}
<section id="hero" class="d-flex justify-cntent-center align-items-center">
    <div id="heroCarousel" class="container carousel carousel-fade" data-ride="carousel">

      <!-- Slide 1 -->
      <div class="carousel-item active">
        <div class="carousel-container">
          <h2 class="animated fadeInDown">Welcome to <span>Text Analytics</span></h2>
          <p class="animated fadeInUp">Text analytics is the automated process of translating large volumes
            of unstructured text into quantitative data to uncover insights,
            trends, and patterns...</p>
          <a href="{% url 'info' %}" class="btn-get-started animated fadeInUp">Read More</a>
        </div>
      </div>

      <!-- Slide 2 -->
      <div class="carousel-item">
        <div class="carousel-container">
          <h2 class="animated fadeInDown">Extract Automated and Quantitative Information From a Text</h2>
          <p class="animated fadeInUp">free-flowing textual sources from which information extraction can distill structured information are legal acts, medical records, social media interactions and streams,  online news, government documents, corporate reports and more.</p>
          <!-- <a href="" class="btn-get-started animated fadeInUp">Read More</a> -->
        </div>
      </div>

      <!-- Slide 3 -->
      <div class="carousel-item">
        <div class="carousel-container">
          <h2 class="animated fadeInDown">Sentiment Analysis</h2>
          <p class="animated fadeInUp">Sentiment analysis is the interpretation and classification of emotions (positive, negative and neutral) within text data using text analysis techniques. Sentiment analysis allows businesses to identify customer sentiment toward products, brands or services in online conversations and feedback.</p>
          <!-- <a href="" class="btn-get-started animated fadeInUp">Read More</a> -->
        </div>
      </div>

      <div class="carousel-item">
        <div class="carousel-container">
          <h2 class="animated fadeInDown">Summary in Only Three Words!</h2>
          <p class="animated fadeInUp">You can try our data analysis tool for text sources, finding a lot of information about a small text, even being able to assign a title with only two or three words!</p>
          <a href="{% url 'textAnalyticsDetails' %}" class="btn-get-started animated fadeInUp">Try</a>
        </div>
      </div>

      <a class="carousel-control-prev" href="#heroCarousel" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon bx bx-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>

      <a class="carousel-control-next" href="#heroCarousel" role="button" data-slide="next">
        <span class="carousel-control-next-icon bx bx-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>

    </div>
  </section><!-- End Hero -->
{% endblock %}

core/templates/core/results.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Resutls{%endblock %} 

{% block body %}

<section class="features">
    <div class="container">
      <div class="section-title">
        <h2>Results</h2>
        <p>
            Here you will find your results.
        </p>
      </div> 
      <div class="row" data-aos="fade-up">
        <div class="col-md-5 order-1 order-md-2">
          <img
            src="{%static 'core/assets/img/features-4.svg'%}"
            class="img-fluid"
            alt=""
          />
        </div>
        <div class="col-md-7 pt-5 order-2 order-md-1">
          <h2>
            Title: <strong>{{title3}}</strong>
          </h2>
          <h4>
              Secondaty Title: <strong>{{title2}}</strong>
          </h4>
          <p class="font-italic">
            Aditional options:
            {% for  element in cb%}
                {{element}}, 
            {%endfor%}
            {% for  element in ct%}
                {{element}}, 
            {%endfor%}
          </p>
          <p>
            <i>Summary: </i>{{summary}}
          </p>
          
          
        </div>
      </div>
      <div class="row" data-aos="fade-up">
        <div class="col-md-5 order-1 order-md-1">
          <img
            src="{% static 'core/assets/img/sentiment-analysis.png'%}"
            class="img-fluid"
            alt=""
          />
        </div>
        <div class="col-md-7 pt-5 order-2 order-md-2">
            <h3>What is the sentiment analysis of the text?</h3>
            <p>The feeling implicit in the text is <strong>{{s}}</strong></p>
        </div>
      </div>

      <div class="text-center">
          <h1>Try another example!</h1>
          <a class="btn btn-primary" href="{% url 'textAnalyticsDetails' %}" role="button">Try</a>
      </div>
    </div>


  </section>
{% endblock %}

core/templates/core/slicing.html
{% extends 'core/base.html' %}
{% load static %}
{% block title%}TextAnalytics{%endblock %}
{%block active_service%}active{%endblock%}
{% block body%}

<section class="features">
  <div class="container">
    <div class="section-title">
      <h2>DEMO SLICING</h2>
      <p>
        Here you can cut a long enough text in different paragraphs to analize. Try it!
      </p>
    </div>

    <div class="row" data-aos="fade-up">
      <div class="col-md-5">
        <img
          src="{% static 'core/assets/img/slice.jpg' %}"
          class="img-fluid"
          alt=""
        />
      </div>
      <div class="col-md-7 pt-4">
        <div class="text-center">
          <h3>How do It works?</h3>
        </div>
        <p class="text-justify">
          In this demonstration, we apply natural language processing, generally
          abbreviated as NLP. This is a branch of artificial intelligence that
          deals with the interaction between computers and humans using natural
          language. The ultimate goal of NLP is to read, decipher, understand,
          and make sense of human languages in a way that is valuable.
        </p>
        <p class="text-justify">
          Please enter a text to be analyzed in the text box below.
        </p>
      </div>
    </div>

    <div class="row" data-aos="fade-up">
      <div class="col-md-5 order-1 order-md-2 align-self-center">
        <div class="text-center">
          <form action="" method="POST">
            {% csrf_token %}
          <tr>
            <td><textarea name="text" id="id_text" required cols="35" rows="18"></textarea></td>
            <br>
            Number of paragraphs:<td><input type="number" min="1" max="5" name="number"></td>           
          </tr>
          <p></p>
          <input type="submit" class="btn btn-primary" value="Send"></input>
        </form>
        </div>
      </div>
      <div class="col-md-7 pt-5 order-2 order-md-1">
        <div class="text-center">
          <h3>Sample Text</h3>
        </div>
        <p class="text-justify">
          Harry Potter and the Chamber of Secrets. In the second book, Harry
          Potter and the Chamber of Secrets, Rowling pits Harry against Tom
          Riddle, Lord Voldemort's "memory" within a secret diary which has
          possessed Ron's younger sister Ginny. When Muggle-born students are
          suddenly being Petrified, many suspect that Harry may be behind the
          attacks, further alienating him from his peers. Furthermore, Harry
          begins to doubt his worthiness for House of Gryffindor, particularly
          considering he discovers he shares Lord Voldemort's ability to
          communicate with snakes via Parseltongue. In the climax, Ginny
          disappears. To rescue her, Harry battles Riddle and the monster he
          controls that is hidden in the Chamber of Secrets. To defeat the
          monster, Harry summons the Sword of Godric Gryffindor from the Sorting
          Hat supplied by Dumbledore's pet phoenix, Fawkes. In doing so,
          Dumbledore later restores Harry's self-esteem by explaining that that
          feat is clear proof of his worthiness of his present house. Harry
          Potter and the Prisoner of Azkaban. In the third book, Harry Potter
          and the Prisoner of Azkaban, Rowling uses a time travel premise. Harry
          learns that his parents were betrayed to Voldemort by their friend
          Peter Pettigrew, who framed Harry's godfather Sirius Black for the
          crimes, condemning him to Azkaban, the wizard prison. When Sirius
          escapes to find Harry, Harry and Hermione use a Time Turner to save
          him and a hippogriff named Buckbeak. When Pettigrew escapes, an
          innocent Sirius becomes a hunted fugitive once again. Harry learns how
          to create a Patronus, which takes the form of a stag, the same as his
          late father's. Harry Potter and the Goblet of Fire. In the previous
          books, Harry is written as a child, but Rowling states that in the
          fourth novel, Harry Potter and the Goblet of Fire, "Harry's horizons
          are literally and metaphorically widening as he grows older."[10]
          Harry's developing maturity becomes apparent when he becomes
          romantically interested in Cho Chang, a student in Ravenclaw house.
          Tension mounts, however, when Harry is mysteriously chosen by the
          Goblet of Fire to compete in the dangerous Triwizard Tournament, even
          though another Hogwarts champion, Cedric Diggory, has already been
          selected. Voldemort uses the Tournament for an elaborate scheme to
          lure Harry into a deadly trap.
        </p>
      </div>
    </div>
  </div>
</section>
{% endblock %}

core/templates/core/textAnalyticsDetails.html
{% extends 'core/base.html' %}
{% load static %}
{% block title%}TextAnalytics{%endblock %}
{%block active_service%}active{%endblock%}
{% block body%}

<section class="features">
  <div class="container">
    <div class="section-title">
      <h2>DEMO</h2>
      <p>
        Here you will find an app that can summarize a text with its own phrase,
        you can also obtain a brigram (2 words) or trigram (3 words) that
        synthesize the central idea of the text very precisely
      </p>
    </div>

    <div class="row" data-aos="fade-up">
      <div class="col-md-5">
        <img
          src="{% static 'core/assets/img/nlpbinary.jpg' %}"
          class="img-fluid"
          alt=""
        />
      </div>
      <div class="col-md-7 pt-4">
        <div class="text-center">
          <h3>How do It works?</h3>
        </div>
        <p class="text-justify">
          In this demonstration, we apply natural language processing, generally
          abbreviated as NLP. This is a branch of artificial intelligence that
          deals with the interaction between computers and humans using natural
          language. The ultimate goal of NLP is to read, decipher, understand,
          and make sense of human languages in a way that is valuable.
        </p>
        <p class="text-justify">
          Please enter a text to be analyzed in the text box below.
        </p>
      </div>
    </div>

    <div class="row" data-aos="fade-up">
      <div class="col-md-5 order-1 order-md-2 align-self-center">
        <div class="text-center">
          <form action="" method="POST">
            {% csrf_token %}
          <tr>
            <td><textarea name="text" id="id_text" required cols="35" rows="18"></textarea></td>
          </tr>
          <p></p>
          <input type="submit" class="btn btn-primary" value="Send"></input>
        </form>
        </div>
      </div>
      <div class="col-md-7 pt-5 order-2 order-md-1">
        <div class="text-center">
          <h3>Sample Text</h3>
        </div>
        <p class="text-justify">
          Harry Potter and the Chamber of Secrets. In the second book, Harry
          Potter and the Chamber of Secrets, Rowling pits Harry against Tom
          Riddle, Lord Voldemort's "memory" within a secret diary which has
          possessed Ron's younger sister Ginny. When Muggle-born students are
          suddenly being Petrified, many suspect that Harry may be behind the
          attacks, further alienating him from his peers. Furthermore, Harry
          begins to doubt his worthiness for House of Gryffindor, particularly
          considering he discovers he shares Lord Voldemort's ability to
          communicate with snakes via Parseltongue. In the climax, Ginny
          disappears. To rescue her, Harry battles Riddle and the monster he
          controls that is hidden in the Chamber of Secrets. To defeat the
          monster, Harry summons the Sword of Godric Gryffindor from the Sorting
          Hat supplied by Dumbledore's pet phoenix, Fawkes. In doing so,
          Dumbledore later restores Harry's self-esteem by explaining that that
          feat is clear proof of his worthiness of his present house. Harry
          Potter and the Prisoner of Azkaban. In the third book, Harry Potter
          and the Prisoner of Azkaban, Rowling uses a time travel premise. Harry
          learns that his parents were betrayed to Voldemort by their friend
          Peter Pettigrew, who framed Harry's godfather Sirius Black for the
          crimes, condemning him to Azkaban, the wizard prison. When Sirius
          escapes to find Harry, Harry and Hermione use a Time Turner to save
          him and a hippogriff named Buckbeak. When Pettigrew escapes, an
          innocent Sirius becomes a hunted fugitive once again. Harry learns how
          to create a Patronus, which takes the form of a stag, the same as his
          late father's. Harry Potter and the Goblet of Fire. In the previous
          books, Harry is written as a child, but Rowling states that in the
          fourth novel, Harry Potter and the Goblet of Fire, "Harry's horizons
          are literally and metaphorically widening as he grows older."[10]
          Harry's developing maturity becomes apparent when he becomes
          romantically interested in Cho Chang, a student in Ravenclaw house.
          Tension mounts, however, when Harry is mysteriously chosen by the
          Goblet of Fire to compete in the dangerous Triwizard Tournament, even
          though another Hogwarts champion, Cedric Diggory, has already been
          selected. Voldemort uses the Tournament for an elaborate scheme to
          lure Harry into a deadly trap.
        </p>
      </div>
    </div>
  </div>
</section>
{% endblock %}